name: "Cuda Test"

on:
  push:
    branches: [ "sycl-develop" ]
  pull_request:
    branches: [ "sycl-develop" ]
  merge_group:
    branches: [ "sycl-develop" ]
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build cuda tests
    runs-on: cp-ubuntu-24.04
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake build-essential g++ nvidia-cuda-toolkit

      - name: Build
        shell: bash
        run: |
          cmake -G Ninja -DCUTLASS_NVCC_ARCHS="90a"
          cmake --build . --target cutlass_test_unit -j 16

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cuda-build
          path: ./
          retention-days: 3

  run-tests:
    name: Run cuda tests
    needs: build
    runs-on: cp-nvidia-gpu
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: cuda-build
          path: ./

      - name: Check GPU availability
        run: |
          nvidia-smi

      - name: Run unit tests
        shell: bash
        run: |
          cmake --build . --target test_unit -j 48
